lsi: false
safe: true
source: "https://github.com/mariajemaria/mariajemaria.github.io"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
title: "Marija Jemuovic's blog"
email: "marija.jemuovic@gmail.com"
description: "Blogging about .NET, Optimizely, Commerce and more"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About: "about"

plugins:
  - jekyll-seo-tag
  
show_excerpts: true
